# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/histfile
HISTSIZE=1000
SAVEHIST=10000
setopt autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/vebly/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

PS1="%F{#00ffff}%n@ %~ %F{#00ffff}%f "

export EDITOR='nvim'

# Aliases
alias zshconf="nvim ~/.zshrc"
alias zshso="source ~/.zshrc"
alias cpwd='pwd | tr -d "\n" | xargs echo -n | xclip -selection clipboard'
alias cmake_ecc='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..'
alias nvimconf='nvim ~/.config/nvim/lua/core/init.lua'
alias nvimbinds='nvim ~/.config/nvim/lua/core/keymaps.lua'
alias nrs='sudo nixos-rebuild switch --flake /home/vebly/.dotfiles'
alias hrs='home-manager switch --flake /home/vebly/.dotfiles'
alias nconf='nvim /home/vebly/.dotfiles/configuration.nix'
#tmuxifier
eval "$(tmuxifier init -)"
eval "$(zoxide init --cmd cd zsh)" #ZOXIDE alias
# Completions
fpath+=/home/vebly/.dotfiles/zsh/completions
#PATH
path+=('/home/vebly/.dotfiles/bin')
